name: ramp
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - pandas>=0.21
  - jupyter
  - matplotlib
  - seaborn
  - scikit-learn>=0.20
  - nilearn
  - keras
  - tensorflow
  - pytorch-cpu
  - torchvision-cpu
  - lightgbm
  - xgboost
  - catboost
  - statsmodels
  - joblib
  - networkx
  - tslearn
  - pyyaml
  - psycopg2
  - sqlalchemy
  - boto3
  - psutil
  - cloudpickle
  - gitpython
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-backend/zipball/master
    - https://api.github.com/repos/pythonprofilers/memory_profiler/zipball/master
    - https://api.github.com/repos/parisots/gcn/zipball/master
    - slidingwindow
