name: ramp
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - pandas>=0.21
  - jupyter
  - matplotlib
  - seaborn
  - keras
  - tensorflow-gpu
  - pytorch
  - torchvision
  - pyyaml
  - psycopg2
  - sqlalchemy
  - boto3
  - psutil
  - cloudpickle
  - gitpython
  - memory_profiler
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-backend/zipball/master
